name: CI

on:
  push:
  pull_request:

jobs:
  php-ci:
    name: PHP Lint & Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: PHP Syntax Check
        run: |
          if ls -1 **/*.php 2>/dev/null; then
            find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l
          else
            echo "No PHP files found, skipping."
          fi

  pwsh-lint:
    name: PowerShell Lint
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Analyze PowerShell Scripts
        shell: pwsh
        run: |
          if (Get-ChildItem -Path . -Recurse -Include *.ps1,*.psm1 -ErrorAction SilentlyContinue) {
            Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning,Error
          } else {
            Write-Host "No PowerShell files found, skipping."
          }
